remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [The Abortion Debate in the US and its Influence on the French and German Abortion Discourse]
subtitle: [Digital Methods - Sciences Po PSIA]
description: [Cecilia KUTTER - Lydie LOUNI - Emma SCHWENTER]
